"use strict";
// Regression for task #137: every file the packaged installer ships (build.files
// + extraResources sources) must exist when it is needed, so "npm run dist"
// never produces an installer that silently omits a module or the backend.
// electron-builder skips missing glob/file entries without failing, so the
// omission would only surface for users as a broken first wizard click.
//
// RED evidence (2026-09-25): a fresh clone of the unify head lacked files the
// build config ships. Files that are generated rather than committed are
// declared in assets/generated-files.json with a stage:
//   commit-time — must exist whenever tests run (checked here)
//   pack-time   — generated by build-backend.sh; `npm run gen:assets` (wired
//                 into npm run dist) verifies or builds them before packaging.
const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");

const installerDir = path.resolve(__dirname, "..");
const pkg = JSON.parse(fs.readFileSync(path.join(installerDir, "package.json"), "utf8"));
const manifest = JSON.parse(
  fs.readFileSync(path.join(installerDir, "assets", "generated-files.json"), "utf8"));

const manifestPaths = new Set(manifest.map((m) => m.path));

function listedShippedPaths() {
  const out = [];
  for (const entry of pkg.build.files) {
    if (entry.includes("**")) {
      const dir = entry.split("/")[0];
      const abs = path.join(installerDir, dir);
      if (fs.existsSync(abs)) for (const f of fs.readdirSync(abs)) out.push(`${dir}/${f}`);
      else out.push(entry);
    } else {
      out.push(entry);
    }
  }
  for (const res of pkg.build.extraResources || []) out.push(res.from);
  return out;
}

test("every shipped file exists or is declared as generated", () => {
  const missingUndeclared = listedShippedPaths()
    .filter((rel) => !fs.existsSync(path.resolve(installerDir, rel)))
    .filter((rel) => !manifestPaths.has(rel));
  assert.deepEqual(missingUndeclared, [],
    "files shipped by the installer are missing from the tree and not declared in " +
    "assets/generated-files.json: " + missingUndeclared.join(", "));
});

test("every commit-time manifest entry exists in the tree", () => {
  const missing = manifest
    .filter((m) => m.stage === "commit-time")
    .filter((m) => !fs.existsSync(path.resolve(installerDir, m.path)))
    .map((m) => m.path);
  assert.deepEqual(missing, [],
    "commit-time shipped files missing (restore from git): " + missing.join(", "));
});

test("manifest has no dead entries (every path is shipped by build config)", () => {
  const shipped = new Set(listedShippedPaths());
  const covered = (rel) => {
    // a shipped directory covers everything under it (e.g. models/ via
    // extraResources), so walk up to the nearest shipped ancestor
    for (;;) {
      if (shipped.has(rel)) return true;
      const i = rel.lastIndexOf("/");
      if (i < 0) return false;
      rel = rel.slice(0, i);
    }
  };
  const dead = [...manifestPaths].filter((p) => !covered(p) && p !== "../scripts/dist");
  assert.deepEqual(dead, [],
    "manifest entries not shipped by build config (remove them or fix build.files): " +
    dead.join(", "));
});